name: Test

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install nox
        run: pip install nox

      - name: Run tests
        run: nox
